### ISSUE TITLE
Evennia Master @ 0.7 

### ISSUE THREAD

**Issue by aliceafterall** [evennia/ainneve#100]
Since Ainneve is a demo game for Evennia, it seems like the time is ripe to update to 0.7. I'll happily write a PR for the changes that are needed, if wanted, but the process is described by Griatch in the forums, and is pretty easy!

Edit: Of course, we have batchcode and such to worry about, but still...

**Comment by Griatch** [comment]
@chainsol: I would suggest you go ahead and do this - no need to ask permissions to *create* a PR. Once the PR is up you ping Dan (@feend78) for review since it might be that he hasn't activated auto-subscriptions to changes in this repo and might not get notifications.

**Comment by aliceafterall** [comment]
Initial PR for this in #101; I need some eyes on the tests that are failing. There's something odd with mock in the setup and tests in world/ are failing. I didn't see anything related to the Player -> Account migration though - it runs just fine.

**Comment by aliceafterall** [comment]
This is implemented in develop - anyone wishing to run Ainneve under 0.7 should use this branch.
