### ISSUE TITLE
Lockfuncs based on traits

### ISSUE THREAD

**Issue by Russell-Jones** [evennia/ainneve#108]
Should there be lockfuncs based on traits provided with Ainneve (to allow things akin to https://github.com/evennia/evennia/wiki/Locks#a-complete-example-of-setting-locks-on-an-object ), or would this be out of scope? The default attr*() lockfuncs only look one level deep, and don't understand the traits system.

**Comment by aliceafterall** [comment]
Yes, I'd think so! We'd welcome a PR for something like that.
