### ISSUE TITLE
Attempting to use @py to view traits crashes server

### ISSUE THREAD

**Issue by aliceafterall** [evennia/ainneve#110]
Attempting to use something like:
```
@py self.msg(self.traits)
```
crashes the server. There are no error messages outputted, and Python and Twistd must be force-killed to be able to fix it.

I have no working theories as to why this is - any help is welcome!

**Comment by aliceafterall** [comment]
Further information: Using `@py self.msg(str(self.traits))` "corrects" this issue, in that it doesn't crash the server.

**Comment by Griatch** [comment]
Is the traitshandler iterable? If so, it may confuse the `msg(text=...)` method you are calling. The `text` outputfunc expects a string; but if it is not getting a string but an iterable, it assumes it's a part of the argument tuple for the `text` outputfunc.

**Comment by aliceafterall** [comment]
@Griatch It doesn't have an `__iter__` method, but if I attempt to call
```
@py for trait in self.traits: pass
```
It also crashes...

**Comment by Griatch** [comment]
@chainsol That more sounds like an error at the serialization level. I take it the Portal log is not saying anything either?

**Comment by aliceafterall** [comment]
@Griatch Yup, no output to any log. Including if I run `evennia start -l`, still no output to any log or the screen.

**Comment by Griatch** [comment]
@chainsol  https://github.com/evennia/evennia/commit/8a1fdb834b6be88e507a0d90f5cc5216590e35ff changes the text-outputfunc handling of Evennia to be a little more lenient - this is such a common error. Does that resolve the problem? I also added it to the develop branch.

**Comment by TehomCD** [comment]
Infinite loop, it looks like. `__getitem__` is called with successively higher values until IndexError is raised, which I think is prevented because `get()` doesn't raise an IndexError if the value is not in cache.

**Comment by aliceafterall** [comment]
@TehomCD So, you mean that we end up essentially calling `__getitem__(0)__`, `__getitem__(1)`, etc? I suppose we should be raising `IndexError` if we don't have that value?

**Comment by TehomCD** [comment]
@chainsol - I think an easier approach might be to define `__iter__` with what you'd expect to see if you iterate through the traits, since that particular behavior of `__getitem__` only occurs if `__iter__` isn't defined. That'd let you keep the existing behavior of `.get()` which might be a pain to change: I wouldn't know how much depends on it not raising IndexError currently.

**Comment by aliceafterall** [comment]
@TehomCD OK, that seems like it would make more sense - yes, it would be a pain to change that behaviour. Plus, `__iter__` is nicer anyway!

**Comment by BlauFeuer** [comment]
`@py for trait in self.traits: pass`
crashes for me, also - more of a hang with no log entry: 
```
  PID     USER  PR  NI   VIRT    RES    SHR  S  %CPU %MEM  TIME+     COMMAND
31384 evennia   20   0  268152  75540   8620 R 100.3  0.5   1:04.05  twistd
```
on master branch, so I have to kill the process then remove the PID file.

**Comment by InspectorCaracal** [comment]
Closing this issue as no longer relevant.
