### ISSUE TITLE
Rework Prototypes for Evennia 0.8

### ISSUE THREAD

**Issue by aliceafterall** [evennia/ainneve#112]
Evennia 0.8 reworked the prototype system, and we make extensive use of it in our world creation code and our character generation.

To fully support Evennia 0.8, we need to rework all of our prototypes and all our code that deals with prototypes (for instance, chargen.py) to use the new prototype system. Currently prototypes are broken, though I've pushed a couple patches that should get Ainneve running on 0.8, but without being able to use the chargen menu's purchase system.

**Comment by friarzen** [comment]
I think this is working well enough now to go ahead and close this issue.
