### ISSUE TITLE
Remove Ainneve's custom combat system and make use of Evennia's TurnBattle contrib

### ISSUE THREAD

**Issue by aliceafterall** [evennia/ainneve#113]
I'd like to further evaluate this idea, but overall the concept is that Ainneve should be a good example for Evennia itself. To further this goal, I'd like to replace our current custom and very broken combat system with the TurnBattle contrib from Evennia.

However, this will need some tweaking to actually work - I'd like to keep our current stat system and such, so I'll need to evaluate how this will all work together. Help is welcome, of course, please comment here with thoughts!

**Comment by serprinss** [comment]
perhaps you should have a look at some combat related issues including #64 and #92

**Comment by aliceafterall** [comment]
Hi! Yes, that's a good idea - due to some life events for me I've been gone for a while.
I'd love to see these issues worked out, however Ainneve isn't built against the latest Evennia branch yet, so that would need to be sorted first. 😁

Due to the COVID-19 pandemic, I'm beginning to have free time again, so I'd welcome contributions to Ainneve, particularly in getting it up-and-running against the latest Evennia release!

Edit: Oh, I've been gone so long people have actually taken over! Even better! Friarzen appears to be contributing and getting Ainneve up-and-running, which is excellent. 😀

**Comment by friarzen** [comment]
On Wed, Apr 8, 2020 at 8:16 AM Nicholas <notifications@github.com> wrote:

> Hi! Yes, that's a good idea - due to some life events for me I've been
> gone for a while.
> I'd love to see these issues worked out, however Ainneve isn't built
> against the latest Evennia branch yet, so that would need to be sorted
> first. 😁
>
I got ya covered for the most part:
https://github.com/evennia/ainneve/pull/114

Still needs a bit of work around the prototypes, since those have been
highly reworked from when Ainneve originally started using them.

--friarzen

**Comment by friarzen** [comment]
I'm gonna close this issue, since the game is starting to go in a different direction entirely, and Griatch is now working on his Evennia Demo game.
