### ISSUE TITLE
traits.clear() fix

### ISSUE THREAD

**Issue by davewiththenicehat** [evennia/ainneve#115]
Hello

Using this class found and resolved a bug.
The unit test fails on line 326 of `traits.py`. The dictionary being looped through changes when it is in the loop.

I was able to resolve by changing the method to.
```python
    def clear(self):
        """Remove all Traits from the handler's parent object."""
        for trait in list(self.all):
            self.remove(trait)
```python

Thanks for offering this code freely.

**Comment by friarzen** [comment]
Thanks, that looks like a good python2->python3 fix.  Added.
