### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by whitenoiseoss** [evennia/ainneve#19]
Write unit tests for everything, once TravisCI is working.

**Comment by ergodicbreak** [comment]
I wrote a minimal example here,  https://github.com/evennia/ainneve/commit/479b9c34a0cab557b50936fa8a04778b8b6f88a4

**Comment by feend78** [comment]
At this point, I think we have unit tests for almost all of the major components we have built. If we continue to build and maintain tests as we go, I don't it warrants a separate issue any longer.
