### ISSUE TITLE
Create Archetype Starter Gear

### ISSUE THREAD

**Issue by whitenoiseoss** [evennia/ainneve#20]
Write and create Starter Gear for each Archetype. This can be a joint effort between a builder and a coder.

On the builder side, what is needed:
Item short and long descriptions (i.e., "This breastplate is made of a fine..." and "a fine, leather breastplate")
What slots the item will take up
Any effects of the item (is it cursed? does it boost a stat? does it give health regen?)

On the coder side:
Create a Typeclass for each abstracted type of item (a Breastplate typeclass for example, from Armor, that is coded to only take up a 'torso' slot)--then all things that only take up the Torso can be Breastplates.
Add to core typeclasses if necessary for decided item effects
Write Spawner/Prototype code to generate these items

**Comment by stefanludlow** [comment]
Something like this? 
https://docs.google.com/spreadsheets/d/1tfFeUwPevYVYujLfVxOrh89Lu7ypVOTBuoZH7yLyiGs/edit?usp=sharing

**Comment by Nadorrano** [comment]
The equip handler is ok with hosting objects that take up more than one slot, however commands have to be reworked a little bit to do that.

Edit: now it is supposed one slot one item, we can use Feet for boots so we don't lose the possibility to have different earrings, rings etc. These items should have slot = ['left ear', 'right ear'], with the meaning "take the first empty slot among these"

**Comment by whitenoiseoss** [comment]
@kaine904 that is a good start yes

**Comment by Nadorrano** [comment]
@ergodicbreak @whitenoiseoss 

Would you like this approach:

``` python
slots = ('head', 'torso', 'feet', 'legs', 'blah', 'blah')
limbs = {'head': 'head'
              'left foot': 'feet',
              'right foot': 'feet'
              'etc': 'etc'}
```

It will allow to print pretty much every possible combination of limbs/slots vs items

**Comment by ergodicbreak** [comment]
@Nadorrano @whitenoiseoss I'm going to split this slots/limbs discussion off into a new issue at #24.

**Comment by ergodicbreak** [comment]
Per #24, we'll have slots and limbs where limbs basically are hittable slots. Eq can take up multiple slots. I think we may want a max number on slots, so for example you could wear multiple necklaces.

**Comment by ergodicbreak** [comment]
@kaine904 would you like to continue this as well?

**Comment by stefanludlow** [comment]
Let's touch base on general status.

**Comment by feend78** [comment]
Hey, I'm interested in helping out with Ainneve, and have been looking at this issue and reading the OA manuals over the past couple days. Is anyone still actively working on this? 

Between the information documented in this issue, the associated EquipHandler and slots discussion referenced above, the wiki, and the OA manuals, I think I could make a stab at it.

**Comment by ergodicbreak** [comment]
@feend78 there hasn't been much Ainneve development lately, but I and probably @whitenoiseoss are available to work with you on this. We would definitely appreciate your contribution.

**Comment by Nadorrano** [comment]
Hi, happy to see that someone is still partecipating in this project! If you are working on this, @feend78, I have a request. That `slot_operator` attribute on items is ugly (is my code), it could be better refactored to `self.db.multi_slot = True/False` or similar. Then line 188 of `equip.py` should be changed to:

``` python
if obj.db.multi_slot:
```

Would you make these changes for me?
 thx and good coding

Edit: only if you think it's a better solution, of course.

**Comment by feend78** [comment]
Hi @Nadorrano, I like that solution, and have changed it and updated the PR.
