### ISSUE TITLE
Design the Arcanist quest

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#26]
I'll be taking this on and writing notes at https://github.com/evennia/ainneve/wiki/World-Content#quest-background, suggestions welcome. See #14 as well.

**Comment by ergodicbreak** [comment]
There is now a rudimentary map of Riverport at https://docs.google.com/spreadsheets/d/12DVWa-X3J8aXSxRQ5u53gDrFjIGq_gPyQvywxuDhhuU/edit?usp=sharing . If you'd like to edit it get in touch and I'll add you to the sheet.

**Comment by Griatch** [comment]
@ergodicbreak 

I like the map! One thing that struck me is the width of the river though; just to check: will boating be supported? Or swimming? Otherwise I suppose those mid-water rooms will never be visited and a double-width river should be enough.

**Comment by ergodicbreak** [comment]
Thanks Griatch, that's a good point. Swimming and boating aren't planned (though would be fun to do).

**Comment by ergodicbreak** [comment]
In light of new work by Kyle we're consolidating this issue into #58 .
