### ISSUE TITLE
Refactor: Use django.conf.settings instead of server.conf.server

### ISSUE THREAD

**Issue by Griatch** [evennia/ainneve#27]
E.g. at 

https://github.com/evennia/ainneve/blob/master/typeclasses/characters.py#L19

the settings module is directly imported as `from server.conf import settings`. This is explicitly _not_ recommended in Django, you should always use `from django.conf import settings`. See [the django settings docs](https://docs.djangoproject.com/en/1.8/topics/settings/#using-settings-in-python-code); there is no need to deviate from the django config mechanic for no reason. This should be changed to the right way wherever it occurs. 
.
Griatch

**Comment by ergodicbreak** [comment]
Thanks Griatch, today I learned something about Django :). Going to push a fix.
