### ISSUE TITLE
Flesh out Character typeclass

### ISSUE THREAD

**Issue by whitenoiseoss** [evennia/ainneve#3]
The Character typeclass is incomplete and needs a great many more methods.

At the time of this issue being written, it is only capable of being skeleton'd out for the most part. It should return certain properties (such as armor) and have any methods that it may need. Keep in mind Character is the base for NPC/Mob/etc. Things specific to things like Shopkeepers and beasts should not go in Character.

While the programming is not difficult, the amount of other things that must be considered is fairly formidable.

**Comment by Nadorrano** [comment]
Hi, I can help with an equip handler that has a number of advantages over the use of a simple dict, error checking, reporting items in the right order (from head to feet) and more. Can be easily expanded to collect modifiers from objects, stats etc. I attached it to the character typeclass as a property (evennia @lazy_property works too, but I don't know if it's risky), slots are loaded at init from a list and the equip is saved as obj.db.equip (a dict).
Bonus: equip, wear, wield (equip primary), hold (equip secondary), remove commands. The wear command is dynamic, it changes to wield or hold if the object has primary or secondary hand as slot.
My commands assume the object has the lock 'equip' and a 'slot' attribute which is a string or a list of strings. Primary and secondary hands are hardcoded as 'right hand', 'left hand' at the moment, assuming all characters right-handed.
If you need this I will fix and write a documentation for it.

**Comment by whitenoiseoss** [comment]
Nadorrano, that sounds like some decent code you have there. However, you're primarily talking about equipment handling, and unfortunately we do not yet have any equipment Typeclasses coded, so that would make those pieces rather difficult.

I also think 'equip' should be part of a Player's Command Set, but the on_equip trigger I would like to put on the weapon typeclass.

I can create issues for writing out the Item typeclass, and from Item will come Weapon, Armor and Shield, if you would like to work on getting combat objects in the game, Nadorrano. Then you could work on a Character being able to equip them, and the methods for showing off a Character's equipment.

**Comment by whitenoiseoss** [comment]
The issue for creating Item is now here: https://github.com/evennia/ainneve/issues/10

**Comment by Nadorrano** [comment]
My at_equip hook at the moment is on the base object typeclass, however I prefer it on the Item typeclass, is more general than weapon I think.
And also why players? You don't want mobs to have an equipment?

See you at #10

**Comment by ergodicbreak** [comment]
I think we have this in hand, we can open more specific issues if necessary.
