### ISSUE TITLE
Overhead mapper

### ISSUE THREAD

**Issue by abbacode** [evennia/ainneve#30]
Is it possible to include a basic overhead mapper to the game which can be toggled on or off?

**Comment by ergodicbreak** [comment]
Yes, but note that we are not building on a coordinate plane, so it's possible the mapper will have some non-logical connections to deal with.

**Comment by ergodicbreak** [comment]
@abbacode are you taking this on or should we close this issue?

**Comment by openadventure** [comment]
I would like to help! I have a few ideas which can be found here: https://docs.google.com/document/d/10C6YXdniCYWOX0HlYtR5RW2EBlsqscJBCJnjVr_-0WQ/pub

**Comment by ergodicbreak** [comment]
@openadventure my greatest apologies, I didn't see your comment until today. I'm closing this particular issue but I'm going to copy the link to your doc over to the wiki here https://github.com/evennia/ainneve/wiki/World-Content#quests-and-area-design . I like that storyline and we can integrate/replace the sketch of the storyline on the wiki now with what you have in your document. Feel free to revise that wiki page as needed.
