### ISSUE TITLE
move become_race from Character to Race

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#32]
@whitenoiseoss I'd like to slim down the `Character` class to emphasize the modularity of Ainneve overall, and I think moving `become_race` to `Race` makes sense (changing the intent to something like `apply_race`). Thoughts?

**Comment by feend78** [comment]
I plan to take this one on next. Now that there is a basis for character traits, it should be fairly easy to build all the necessary chargen support functionality into a world/races.py module, similar to how archetypes was done.
