### ISSUE TITLE
move primary/secondary traits out of Character to integrate with Archetypes

### ISSUE THREAD

**Issue by ergodicbreak** [evennia/ainneve#33]
Part of the effort to slim down `Character` and make things modular. Since it's really Open Adventure archetypes that define primary traits, and we derive secondary traits from primary traits, I propose integrating primary/secondary traits with archetype and moving them out of Character altogether. 

By integrating I mean the archetype base template will instantiate Traits, like we have in `Character` at the moment. 

This will probably include moving the function `base_stat` as well, which currently calculates secondary traits.

**Comment by stefanludlow** [comment]
I second that.

**Comment by feend78** [comment]
I'd like to take a shot at this, @ergodicbreak, as it seems this will have to be addressed before I can continue with the equipment effects/abilities part of the starter equipment PR. 

I was sort of envisioning that individual Archetype classes that are there now could go away, and the data they encapsulate could be moved into the archetypes module. I'd then write a series of functions that would manipulate attributes on the character using that data, such as setting up a collection of traits on the character during character generation or adding a Talent to it while leveling up. So under normal circumstances, the traits collection of `Trait` objects on the character handles stat checks and buffs/debuffs/etc., and the archetypes module is only imported when the character needs to make archetype-related changes to itself.

Does that sound roughly like what you were thinking? Is there a reason I'm missing to make each Archetype a class of its own?

**Comment by ergodicbreak** [comment]
Looking back on it I made them classes to facilitate base trait templates and dual archetypes, but you could do that with dictionaries and functions, it might require a little more code I suppose.

Your overall plan sounds good, if by "the traits collection of Trait objects on the character handles stat checks and buffs/debuffs/etc." you mean traits can report their value and increase/decrease themselves but they aren't actually where we put OA rules for how stats are checked and so forth.

**Comment by feend78** [comment]
Yes, I was mostly planning on using the Trait class that's in master already. It has the base value/increase/decrease functionality mostly fleshed out. I assume that the traits within the traits collection will be accessed directly by the rulebook module or passed into rulebook functions from within a Command for the actual checks. The traits collection itself will probably just be a plain dict, or one tricked out so you can access the Trait instances either as `traits['strength']` or `traits.strength`.

**Comment by ergodicbreak** [comment]
Yes you're on the right track, thanks @feend78 .
