### ISSUE TITLE
Write AinneveArchetype skeleton

### ISSUE THREAD

**Issue by whitenoiseoss** [evennia/ainneve#5]
AinneveRaces can be used as an example for this code. Whoever does this will need to write the Archetype class (new Python class) and then figure out if anything and if so what goes into the module's **init**.py.

In addition, this module will need to be tied into Plugger.

**Comment by ergodicbreak** [comment]
I'm going to have a go at this, if someone has started on it please chime in.

**Comment by ergodicbreak** [comment]
Now working on this in branch https://github.com/evennia/ainneve/tree/archetypes.

**Comment by ergodicbreak** [comment]
@ChrisHC I was considering merging my branch to master. Would you like to make a PR with what you have for archetypes? Perhaps we could merge the more developed one or combine the good parts of both branches.

**Comment by whitenoiseoss** [comment]
VoidFox also did this. I merged VoidFox's so we would stop wrecking on this issue.

**Comment by ergodicbreak** [comment]
Talked to VoidFox in IRC and this was just an accidental merge of unrelated code, going to keep this issue open for now.

**Comment by ergodicbreak** [comment]
Remaining todo:
- update dual archetypes with new archetype name (e.g. 'Warrior-Scout'). Simple way, add a 'name' string, fancy way, update subclass dynamically
- Tie into plugger

archetypes branch is up to date with master, someone else can take the ball on this if they'd like a nice self-contained task.

**Comment by ergodicbreak** [comment]
Added naming in 34cb6249c828e57317b6d4560baa0fc49a1a0cd6

**Comment by ergodicbreak** [comment]
Plugger is not done, but merging this to get the ball rolling on character creation. We can add plugger later as needed.
