### ISSUE TITLE
Feature Request: Changes to the TraitFactory

### ISSUE THREAD

**Issue by Griatch** [evennia/ainneve#54]
@feend78, @ergodicbreak, @whitenoiseoss 

I have looked more closely into the handling of Traits/TraitFactory after a user asked me about implementation details. I have some suggestions from the perspective of core Evennia: 
1. To keep consistency with Evennia's source, I suggest that the `TraitFactory` class is renamed to `TraitHandler` since it works basically like a handler in Evennia (from the outside it looks like an object on which you access member-traits). 
2. The internal property `dbobject` (for the `_SaverDict`) is potentially confusingly named since "dbobject" has a legacy use in Evennia to mean "ObjectDB" and other base django model classes. Maybe I'm the only one confused by it, but I would recommend renaming it to `attr_dict` or even `saver_dict` for clarity. 
3. That said, I don't think it's really all that necessary to have TraitFactory/Handler accept a separately created Attribute dict as input. This could just as well be a string for the name of the Attribute you want to use or, better, child-classes of handlers hard-coding the storage-name (like how Tag/AttributeHandlers do it). The reason for this is partly that it muddles the API (why should the user need to know they must initialize a Attribute dict when it's only ever used internally?) but mainly because passing the `_SaverDict` itself around is potentially not future proof. That `_SaverDicts` retain their link to the database is an implementation _side-effect_ of Attributes; Their names start with a `_` for a reason - I'm not comfortable with them being passed around and themself used as a main unit of data; Attribute internal implementation may (not saying it will, but may) change at some point. Letting the TraitFactory itself manage its own storage is also in line with how all other handlers in Evennia works (the standard is in fact to pass in the typeclass itself and have the handler access it to set up its storage as needed).  
4. There is no need to fully comply with how handlers are used in Evennia, but you should be aware that _all_ evennia handlers use handler methods named `get/add/remove/clear/all` to access and modify internal state. In Evennia's case this is because handlers generally require extensive extra arguments (so a plain property assignment is not enough). But it's worth to keep in mind. 
5. As far as I can tell there does not seem to be a reason to not use the `evennia.utils.utils.lazy_property` decorator for assigning `traits`/`skills`properties on `Character`, similarly to how it's done for `equip`.

**Comment by feend78** [comment]
@Griatch: all of these changes seem fairly straightforward and easy to implement. I originally didn't put add/remove/clear on the TraitFactory partly because I like the idea of them being fairly static, in that I had not anticipated a use case where a new Trait would be added to or removed from the traits collection on the fly, and partly because of my unfamiliarity with Evennia and the structure of its other handlers. However, if it's going to be called "Handler," it seems like it should probably comply with the rest of the handler interface.

I had seen the `lazy_property` in there on EquipHandler, but hadn't looked into exactly how it differs from `@property`, so I wasn't sure it'd be ok to use. Given your endorsement of it, I'll switch it along with these other changes you've requested.

**Comment by Griatch** [comment]
@feend78 

Cool. :) To explain, `@lazy_property` is basically an on-demand loader: It potentially speeds up original initialization of an object and makes sure to not initialize handlers until they are actually accessed in some form. It may or may not save some memory, but should at least not hurt. :) 

Another thing I forgot to mention is that `_SaverDict` actually only exists for Attributes created with the `.db` wrapper (which makes them even more implementation sensitive): they are needed as an intermediary to allow on-.db-handler updates, such as `obj.db.mydict['foo'] = 'bar'`, while having it automatically save to the database (otherwise you'd have to re-assign the Attribute every time you changed an element of a mutable). This is all just a thin wrapper on top of the actual `AttributeHandler`though, which handles dynamically assigned Attribute names. It's accessed via for example `obj.attributes.add("_traits", {})`.

**Comment by feend78** [comment]
Go ahead and assign this one to me if you want, @ergodicbreak. I've already made the code changes locally; just have to update docs and tests and it'll be ready.
