### ISSUE TITLE
Enhance return_appearance on Character Typeclass

### ISSUE THREAD

**Issue by feend78** [evennia/ainneve#57]
The character typeclass is currently using the  default `return_appearance` hook implementation from DefaultCharacter/DefaultObject, which isn't aware of the difference between inventory items and equipped items, and displays all of the character's items to anyone looking at it.

Ideas for improvements to `return_appearance`:
- Perception checks to give more or less detailed messages to the looker, including archetype, race, possibly indicators for health and/or stamina.
- Hide contents of character inventory from lookers.
- Show equipped items to lookers.

**Comment by aliceafterall** [comment]
I've mostly completed this, but I wanted to ask, how difficult should the perception check be for each of race, archetype, health, and stamina?

For health and stamina, should it be perception, or the Medicine skill?

I've already completed the rest of it - the return_appearance hook doesn't show inventory items, only equipped items, and where they're equipped ( right arm, left arm, head, etc )
