### ISSUE TITLE
Set up base Room and Exit typeclasses

### ISSUE THREAD

**Issue by feend78** [evennia/ainneve#59]
In IRC, we've had a few discussions about implementing some baseline typeclass features for rooms and exits. I wanted to continue that here. Some topics that have come up:
- Using `ExtendedRoom` as the parent class of our `Room` typeclass
- Rooms incorporating a linear range / size that affects room capacity and combat
- Rooms having terrain types and corresponding MV costs to enter
- Use of "slow exits"
- Ability to view an exit's destination through a room's Exits

**Comment by feend78** [comment]
So @ergodicbreak, I was thinking a bit more about how to handle parties, positioning, room capacity, and the linear range. I don't really like the idea of a truly one-dimensional model, with one character per space on the range field, with characters presumably "jumping over" one another. 

I think a good balance between a truly linear system and the complexity of tracking positions on a 2D map would perhaps be to specify the range field as a length and width, then consider only the length dimension for combat purposes, and only look at the width dimension for passing and formation considerations between allies.

**Comment by ergodicbreak** [comment]
@feend78 that's a good idea, and would work great for tunnels vs. open fields and the like.

**Comment by feend78** [comment]
Okay, so I have started a branch and made the changes to Room discussed above. I added a mv_cost property to it, which will be used by our Exit typeclass to deduct from characters' MV trait. This brings up the need to have those movement points regenerate. I assume that we'll be using Script objects to handle this, and that each character will have its own.

It makes me wonder whether we couldn't incorporate MV points into combat instead of action points. 

Though also, as I'm starting to look toward building combat, I should say that I'm not against sticking with the OA-style turn based combat system, especially given that there's a turn-based combat tutorial in the Evennia docs that could be a starting point.

**Comment by ergodicbreak** [comment]
I like the idea of incorporating MV points into combat (I'd have to check the OA rules again to see if they already are a factor).

On doing a turn-based combat, I'm not necessarily opposed but I think it would change the feel from a H&S game to more of a RP game -- which may not be a bad direction to go, especially given that we've talked about including RPsystem. What do you think about that change in direction (we probably should move this to the combat issue).

**Comment by feend78** [comment]
I took a look at the slow_exit module from contrib. I think we can use it for some inspiration, but for interaction with character traits in Ainneve, I don't think slow_exit by itself will work.

**Comment by feend78** [comment]
Completed by PR #61
