### ISSUE TITLE
Write Character Generation

### ISSUE THREAD

**Issue by whitenoiseoss** [evennia/ainneve#6]
This will involve creating a Room typeclass for character generation, a CmdSet for the character generation commands, and an understanding of the Character typeclass.

This will utilize MenuNode from the contrib unless decided otherwise.

This is not terribly difficult, but has a lot of moving pieces.

**Comment by ergodicbreak** [comment]
@whitenoiseoss will write out the framework to give everyone something to work from.

**Comment by ergodicbreak** [comment]
A note that @feend78 is moving on this.

**Comment by feend78** [comment]
This was completed by PR #56
