### ISSUE TITLE
Build a limited, wilderness "training" area within Riverport

### ISSUE THREAD

**Issue by feend78** [evennia/ainneve#67]
Before we get too much farther on the combat and other game systems, we could use a small grouping of rooms that can serve as a testing ground. 

This will be the first permanent parts of the Ainneve game world, and it should be comprised of 5-7 rooms near the center of Riverport. To anchor this area to the maps that @kylemecklem has created, it should include the bridge near the center of the town at coordinates (36, 18) (see [Riverport.pdf](https://github.com/evennia/ainneve/files/203779/Riverport.pdf)), as well as one room along the main east-west road, and 3-5 additional rooms north of the road that will be semi-wilderness along the river shore, and can provide some low-level enemies to train against.

Any interested builders should comment on this issue if you are interested in working on this or have questions.

**Comment by j3b4** [comment]
I'd love to contribute here. I presume the ideal way to contribute built areas is through Batch code.

**Comment by feend78** [comment]
Hi @j3b4, thanks for stepping up!

Batch code would certainly work, but in the wiki, we have sort of emphasized using `@batchcommand` scripts instead of `@batchcode` to try and lower the learning curve for those who might be interested in building content but not necessarily learning to code. 

We have also extended Ainneve's base `Room` typeclass with some additional properties, along with builder commands to set them. See the [Ainneve Builder Docs](https://github.com/evennia/ainneve/wiki/Builder-Documentation) wiki page for examples and best practice suggestions.

**Comment by ergodicbreak** [comment]
I'm going to build the _Dancing Dragon_ inn (at coordinates 28. 17 -- see the more detailed map at https://docs.google.com/document/d/10C6YXdniCYWOX0HlYtR5RW2EBlsqscJBCJnjVr_-0WQ/pub ) as a starting location for new characters. It's on the same road as the bridge.

**Comment by feend78** [comment]
I think the Grassy Meadow is working well enough for the original intent of this task. We can make separate issues for other areas like the _Dancing Dragon_.

@j3b4 and @ergodicbreak: I'm quite close to finishing combat for Ainneve. I'm hoping you would be up for checking it out and giving feedback once I get a PR together. I hope things are well with you guys!

**Comment by j3b4** [comment]
Hi Dan,

Yes things are well, though I've been away from Evennia for several months.
It would be nice to start working on a few projects again.
