### ISSUE TITLE
Traceback on @Open

### ISSUE THREAD

**Issue by stefanludlow** [evennia/ainneve#74]
When using the following @batchcommand ([PasteBin Link of Batchcommand](http://pastebin.com/SEjRQA2A)) in a fresh install of Ainneve, @open commands fail with the following traceback: 

```
28/28: @open East;e,West,w = arena#5                  
TypeError: object of type 'Character' has no len()
An untrapped error occurred. Please file a bug report detailing the steps to reproduce.
(Traceback was logged 2016-08-07 22:21:55-0400).
```

I can confirm that the same @batchcommand works just fine in production Evennia

Edit: adding console log: http://pastebin.com/NJmED4GU

**Comment by feend78** [comment]
In the example above, you have a syntax error. The comma between 'West' and 'w' should be a semicolon.

If correcting that does not fix the error, you should [open an issue for Evennia](https://github.com/evennia/evennia/issues/new) directly, as Ainneve has not overridden any of the fundamental building commands. We've only added the `@terrain` and `@rangefield` commands to set those properties on your rooms when building.

That said, I'm super stoked to see someone interested in doing some work with Ainneve (and prodding  me into doing more)! so please keep asking questions, @stefanludlow, and I'll do my best to answer them.
