### ISSUE TITLE
Design the world of Ainneve

### ISSUE THREAD

**Issue by whitenoiseoss** [evennia/ainneve#8]
Design the world of Ainneve!

**Comment by hallofnights** [comment]
I've sketched out a crude representation of the island. I'm no cartographer and the scale is a bit wacky, but I think it should work for development purposes. 
![ainneve_map](https://cloud.githubusercontent.com/assets/5454467/8299183/de5e43c4-1942-11e5-9a18-f7f0781bf8b6.png)

**Comment by MrDowntempo** [comment]
Let's get this going so we know what we're doing when we're ready to build rooms. I think before we start drawing maps we need a bit more of an idea of what we're dealing with. What races do we have? What are their cultures like? What environments/climates do they live in and how has that affected their cultures? What's the overall tech available? etc.

If we're going fairly generic we've got tree elves in the forest, men in the plains, mastering horses, dwarves in the mountains. Maybe another 'race' of men, savage, or barbaric, or peaceful but less tech advanced?

**Comment by ergodicbreak** [comment]
@MrDowntempo, I started a thread on the ML to sort out just these kinds of questions, here https://groups.google.com/forum/?fromgroups#!category-topic/evennia/pixvX8mncn0 .

For speed and simplicity's sake we're going to concentrate our content in three main quests, each composed of three tasks (one per level in this three level example game). Let's start simple and focus on designing the first quest. Going to close this issue for now as I think it's too big to keep our focus on track.
