### ISSUE TITLE
Sdescs will not evaluate between a and an based on potential {}, e.g. a yellow rat, an orange rat

### ISSUE THREAD

**Issue by stefanludlow** [evennia/ainneve#82]
When dynamic descriptions are created, there is currently nothing in place to automatically evaluate them for grammatical correctness. 

The logic should be, for sdescs: 
If the first letter of the second word in a string beginning with "a" or "an" is a consonant, then the first word of the string should be "a" 
If the first letter of the second word in a string beginning with "a" or "an" is a vowel, then the first word of the string should be "an"

Griatch suggests somewhere around region https://github.com/evennia/evennia/blob/master/evennia/contrib/rpsystem.py#L443 for a place to potentially install something or other to fix.

**Comment by Griatch** [comment]
This should probably be made as a feature request against Evennia rather than against Ainneve.

**Comment by feend78** [comment]
I wrote this up as Issue/Feature request [#1028](https://git.io/viJiD) in Evennia.
