### ISSUE TITLE
NPC AI - Behavior Trees

### ISSUE THREAD

**Issue by stefanludlow** [evennia/ainneve#83]
Issue created for @andrei-pmbcn to track development on behavior tree AI contrib. This will cover AI for Ainneve.

**Comment by andrei-pmbcn** [comment]
I'll start working on it in at most two days' time.

**Comment by feend78** [comment]
@andrei-pmbcn,

I've seen some of your discussion about your AI system in the IRC channel, and I'm curious why you wanted to implement it with custom models? Is there some query that is extra complicated for loading AI info? I have something of an aversion to including custom models unless absolutely necessary, but I'm willing to be convinced.

**Comment by andrei-pmbcn** [comment]
I've finished coding the AI system (unless there were a few bugs I didn't catch) and written the documentation for it. As per my discussions with @feend78 over IRC, I am using scripts instead of custom models.

**Comment by stefanludlow** [comment]
@andrei-pmbcn, just wanted to ping you regarding this particular item?

**Comment by feend78** [comment]
In the combat branch, I included basic combat AI for NPCs tagged "AGGRESSIVE". Per discussion on IRC, we're going to consider that good enough for our initial iteration.
