### ISSUE TITLE
Create NPC shop(s)

### ISSUE THREAD

**Issue by feend78** [evennia/ainneve#85]
Currently in Ainneve, the chargen menu provides the opportunity to "purchase" equipment, but we do not yet have an in-game NPC shop.

Shops can generally follow the structure of the [NPC Shop Tutorial](https://github.com/evennia/evennia/wiki/NPC%20shop%20Tutorial).

**Comment by maxsond** [comment]
I'm claiming this task: https://trello.com/b/JfURQL0D/ainneve-npc-shop
Also see https://groups.google.com/forum/#!category-topic/evennia/ainneve/nJKUl2QDuiU
