### ISSUE TITLE
Ever Expanding Linebreaks in Chargen

### ISSUE THREAD

**Issue by stefanludlow** [evennia/ainneve#93]
In chargen, linebreaks expand in width until there is a horizontal scroll on the screen.

**Comment by feend78** [comment]
I think I understand what you're describing here. The horizontal line between the text and options when displaying a menu node gets quite long under certain circumstances (I think primarily having to do with color/ansi codes).

It's an issue with EvMenu, and it's been in the back of my mind to put together a test case and create an issue for it against the main Evennia repo, but I haven't made time to do so yet.
