### ISSUE TITLE
settings secret key has been publicized

### ISSUE THREAD

**Issue by texdarkstar** [evennia/ainneve#94]
I'm not sure if it matters, not sure how exactly it is used, but the secret key in server\conf\settings.py is actually included in the repo.

    # The secret key is randomly seeded upon creation. It is used to sign
    # Django's cookies. Do not share this with anyone. Changing it will
    # log out all active web browsing sessions. Game web client sessions
    # may survive.

Posting this as an issue, because I thought it better to spam than have a possible security risk.

**Comment by Griatch** [comment]
It's not a huge deal, but if it's included one should probably point out that the user should change it (just plop some new chars in there) before making theor ainneve game public.

**Comment by texdarkstar** [comment]
Okay. What is this key used for specifically though? Should I move this to the forums?
